const PROGRAM=[
 {tab:"Glutes",title:"Glutes & posterior chain",description:"Glute growth, hip stability and clean hinge mechanics. About 45 minutes.",warmup:["Hip-flexor stretch · 45s/side","Adductor rock-back · 8/side","90/90 switches · 8/side","Glute bridge · 12"],cardio:{timing:"Finish",duration:"5–10 min",gym:"Stair stepper, incline walk or bike at a sustainable pace.",home:"Bike or jump rope at a sustainable pace."},exercises:[
  {name:"Glute drive",sets:3,reps:"8–12",rest:90,gym:"Glute drive machine. Warm-up: 110 lb. Working target: 176 lb only for clean reps.",home:"Bench hip thrust with dumbbell or kettlebell.",cue:"Stop or reduce weight when pelvic position, range, or glute tension changes."},
  {name:"Deadlift — Week A",sets:3,reps:"8–10",rest:90,gym:"Barbell Romanian deadlift.",home:"Dumbbell or kettlebell Romanian deadlift.",cue:"Push hips back; keep ribs stacked and the load close."},
  {name:"Deadlift — Week B",sets:3,reps:"8–10/side",rest:75,gym:"B-stance or single-leg Romanian deadlift.",home:"B-stance or supported single-leg RDL.",cue:"Rear foot is a kickstand; stop before hip rotation."},
  {name:"Posterior-chain accessory",sets:3,reps:"12–15",rest:60,gym:"45-degree back extension. Clamshell only if completely pain-free.",home:"Bench back extension or gentle clamshell if pain-free.",cue:"Skip any movement that reproduces glute-med pain; prioritize control."}]},
 {tab:"Posture",title:"Back, shoulders, neck & posture",description:"Higher-rep stamina so the right muscles share the load of desk work and holding Ivy.",warmup:["Neck nods · 6","Wall slides · 8","Thoracic rotations · 6/side"],cardio:{timing:"First",duration:"5–10 min",gym:"Easy rower, ski erg or bike.",home:"Easy bike or relaxed jump-rope intervals."},exercises:[
  {name:"Chest-supported row",sets:3,reps:"15–20",rest:60,gym:"Incline bench dumbbells, cable or machine.",home:"Incline bench + dumbbells.",cue:"Keep neck long; lead with elbows without shrugging."},
  {name:"Lat pulldown / assisted pull-up",sets:3,reps:"15–20",rest:60,gym:"Neutral-grip pulldown or assisted pull-up.",home:"Dumbbell pullover or band pulldown if available.",cue:"Pull elbows toward back pockets with ribs down."},
  {name:"Chest-supported Y raise",sets:3,reps:"15–20",rest:45,gym:"Incline bench or cable, very light.",home:"Incline bench + very light dumbbells.",cue:"Thumbs up and shoulders away from ears."},
  {name:"Face-pull pattern",sets:3,reps:"15–20",rest:45,gym:"Rope face pull.",home:"Prone W raise or reverse snow angel.",cue:"Finish with hands beside ears; move slowly."},
  {name:"Wall angels",sets:2,reps:"15–20",rest:45,gym:"Wall angels.",home:"Wall angels.",cue:"Keep ribs stacked; use a pain-free range."},
  {name:"Farmer carry",sets:3,reps:"30–60 sec",rest:45,gym:"Heavy dumbbells or kettlebells.",home:"Dumbbells or kettlebell.",cue:"Walk tall. Reach 60 seconds before adding weight."}]},
 {tab:"Functional",title:"Functional full body",description:"Stamina for holding Ivy, carrying bags and moving confidently.",warmup:["Cat-cow · 6","Hip hinge drill · 8","Shoulder CARs · 5/side"],cardio:{timing:"First",duration:"15 min",gym:"Rower or ski erg intervals: 1 minute firm / 1 minute easy.",home:"Bike intervals or bike + jump-rope mix."},exercises:[
  {name:"Kettlebell deadlift",sets:3,reps:"15–20",rest:60,gym:"Kettlebell or trap bar, light-to-moderate.",home:"Kettlebell or dumbbells.",cue:"Drive the floor away and keep the load close."},
  {name:"Half-kneeling one-arm press",sets:3,reps:"15–20/side",rest:60,gym:"Cable, dumbbell or kettlebell.",home:"Dumbbell or kettlebell.",cue:"Squeeze kneeling-side glute; keep ribs down."},
  {name:"Supported one-arm row",sets:3,reps:"15–20/side",rest:60,gym:"Bench, cable or machine.",home:"Bench + dumbbell or kettlebell.",cue:"Brace through the support arm without twisting."},
  {name:"Dead bug with pullover",sets:3,reps:"10–15/side",rest:45,gym:"Light dumbbell or cable.",home:"Light dumbbell.",cue:"Move only as far as the lower ribs stay controlled."},
  {name:"Front-rack or suitcase carry",sets:3,reps:"30–60 sec",rest:45,gym:"Dumbbells or kettlebells.",home:"Dumbbells or kettlebell.",cue:"Brace and breathe; reach 60 seconds before adding weight."},
  {name:"Floor-transfer practice",sets:2,reps:"3–5/side",rest:45,gym:"Half get-up with a light kettlebell.",home:"Bodyweight, shoe or light kettlebell.",cue:"Move slowly; this is coordination, not a max lift."}]}
];
const KEY="strongLeanJournalV1";let state=JSON.parse(localStorage.getItem(KEY)||'{"sessions":[]}');let day=0,activeView="workout",remaining=60,selectedRest=60,timerId=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function draftKey(){return `strongLeanDraft-${new Date().toISOString().slice(0,10)}-${day}`}
function loadDraft(){return JSON.parse(localStorage.getItem(draftKey())||'{"sets":{},"notes":""}')}
function persistDraft(){const sets={};document.querySelectorAll("[data-ex]").forEach(i=>{sets[`${i.dataset.ex}-${i.dataset.set}-${i.dataset.field}`]=i.type==="checkbox"?i.checked:i.value});localStorage.setItem(draftKey(),JSON.stringify({sets,notes:$("notes").value}))}
function render(){const p=PROGRAM[day],loc=$("location").value,d=loadDraft();$("dayTabs").innerHTML=PROGRAM.map((x,i)=>`<button class="${activeView==="workout"&&i===day?"active":""}" data-day="${i}">${i+1} · ${x.tab}</button>`).join("")+`<button class="${activeView==="progress"?"active":""}" id="progressTab">✨ Progress</button>`;$("workoutView").hidden=activeView!=="workout";$("progressView").hidden=activeView!=="progress";if(activeView==="progress"){renderProgress();bindTabs();return}$("dayKicker").textContent=`Day ${day+1}`;$("dayTitle").textContent=p.title;$("dayDescription").textContent=p.description;$("warmup").innerHTML=p.warmup.map(x=>`<span class="chip">${x}</span>`).join("");$("cardioTiming").textContent=`${p.cardio.timing} · ${p.cardio.duration}`;$("cardioDuration").textContent=p.cardio.duration;$("cardioText").textContent=p.cardio[loc];$("exerciseList").innerHTML=p.exercises.map((e,i)=>`<article class="card"><div class="exercise-head"><span class="exercise-num">${i+1}</span><div><strong>${e.name}</strong><p class="meta">${e.sets} sets · ${e.reps} · ${e.rest}s rest<br>${e[loc]}</p><p class="cue">Cue: ${e.cue}</p></div></div><div class="sets">${Array.from({length:e.sets},(_,s)=>{const base=`${i}-${s}`;return `<div class="set-row"><span>${s+1}</span><input data-ex="${i}" data-set="${s}" data-field="weight" inputmode="decimal" placeholder="lb" value="${esc(d.sets[base+"-weight"]||"")}"><input data-ex="${i}" data-set="${s}" data-field="reps" inputmode="numeric" placeholder="reps" value="${esc(d.sets[base+"-reps"]||"")}"><input data-ex="${i}" data-set="${s}" data-field="done" type="checkbox" ${d.sets[base+"-done"]?"checked":""}></div>`}).join("")}</div></article>`).join("");$("notes").value=d.notes||"";bindTabs();document.querySelectorAll("[data-ex]").forEach(i=>i.onchange=persistDraft)}
function bindTabs(){document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{if(activeView==="workout")persistDraft();activeView="workout";day=+b.dataset.day;render()});$("progressTab").onclick=()=>{if(activeView==="workout")persistDraft();activeView="progress";render()}}
function startOfWeek(date){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function sessionTotals(session){let reps=0,volume=0;Object.entries(session.sets||{}).forEach(([key,value])=>{if(!key.endsWith("-reps"))return;const base=key.slice(0,-5),r=Number(value)||0,w=Number(session.sets[base+"-weight"])||0,done=session.sets[base+"-done"];if(done||r){reps+=r;volume+=r*w}});return{reps,volume}}
function renderProgress(){const sessions=state.sessions||[],now=new Date(),thisMonday=startOfWeek(now),weekMap=new Map();let reps=0,volume=0;sessions.forEach(s=>{const wk=startOfWeek(s.date).toISOString().slice(0,10);if(!weekMap.has(wk))weekMap.set(wk,new Set());weekMap.get(wk).add(Number(s.day));const t=sessionTotals(s);reps+=t.reps;volume+=t.volume});const completedWeeks=[...weekMap.values()].filter(days=>days.size>=3).length;const currentDays=weekMap.get(thisMonday.toISOString().slice(0,10))||new Set();$("progressStats").innerHTML=[["🌿",completedWeeks,"weeks completed"],["💪",sessions.length,"workouts saved"],["✨",reps.toLocaleString(),"reps logged"],["🏋️",Math.round(volume).toLocaleString(),"lb moved"]].map(([icon,value,label])=>`<div class="stat-card"><div class="stat-icon">${icon}</div><div class="stat-value">${value}</div><div class="stat-label">${label}</div></div>`).join("");$("progressMessage").textContent=sessions.length?currentDays.size===3?"Full week complete—you showed up for all three. 🌟":`${currentDays.size} of 3 sessions complete this week. Every one counts.`:"Save your first workout and your garden will begin to bloom.";const weeks=[];for(let i=7;i>=0;i--){const d=new Date(thisMonday);d.setDate(d.getDate()-i*7);const key=d.toISOString().slice(0,10),count=(weekMap.get(key)||new Set()).size;weeks.push(`<div class="week-flower ${count>=3?"complete":""}"><div><div class="bloom">${count>=3?"🌸":"🌱"}</div><small>${count}/3 · ${d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></div></div>`)}$("weekGarden").innerHTML=weeks.join("");$("weeklyDays").innerHTML=PROGRAM.map((p,i)=>`<div class="weekly-day ${currentDays.has(i)?"done":""}"><div class="check">${currentDays.has(i)?"✅":"○"}</div><strong>${p.tab}</strong></div>`).join("");const recent=sessions.slice(-5).reverse();$("recentWins").innerHTML=recent.length?recent.map(s=>{const t=sessionTotals(s);return`<div class="win-row"><div><strong>${esc(PROGRAM[s.day]?.tab||s.workout)}</strong><div class="meta">${new Date(s.date).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</div></div><div class="meta">${t.reps.toLocaleString()} reps${t.volume?` · ${Math.round(t.volume).toLocaleString()} lb`:""}</div></div>`}).join(""):`<div class="empty-progress">Your saved workouts will appear here.</div>`}
function status(t){$("status").textContent=t}
function fmt(s){return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function setTimer(){ $("timerDisplay").textContent=fmt(remaining)}
$("location").onchange=render;$("notes").oninput=persistDraft;$("saveWorkout").onclick=()=>{persistDraft();const d=loadDraft();state.sessions.push({date:new Date().toISOString(),day,workout:PROGRAM[day].title,location:$("location").value,...d});localStorage.setItem(KEY,JSON.stringify(state));status("Workout saved on this phone. Export JSON whenever you want a backup.")};
document.querySelectorAll("[data-rest]").forEach(b=>b.onclick=()=>{clearInterval(timerId);timerId=null;selectedRest=remaining=+b.dataset.rest;setTimer();$("timerToggle").textContent="Start"});
$("timerToggle").onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$("timerToggle").textContent="Start";return}if(remaining<=0)remaining=selectedRest;$("timerToggle").textContent="Pause";timerId=setInterval(()=>{remaining--;setTimer();if(remaining<=0){clearInterval(timerId);timerId=null;$("timerToggle").textContent="Start";navigator.vibrate?.([150,80,150])}},1000)};
function exportJournal(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download=`strong-lean-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
$("exportButton").onclick=exportJournal;$("headerExport").onclick=exportJournal;
$("importInput").onchange=async e=>{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.sessions))throw new Error("Invalid journal file");state=data;localStorage.setItem(KEY,JSON.stringify(state));status("Journal imported.")};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();setTimer();
